apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
  namespace: taskflow
type: Opaque
stringData:
  TASKFLOW_DATABASE_URL: "postgresql+asyncpg://postgres:root@taskflow-postgres:5432/taskflow"
  POSTGRES_PASSWORD: "root"
