
"""add lease_expires_at to jobs

Revision ID: a7a5249445a4
Revises: 881e75ea5295
Create Date: 2026-01-13 21:51:01.392317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7a5249445a4'
down_revision: Union[str, Sequence[str], None] = '881e75ea5295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_definitions',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('handler_ref', sa.Text(), nullable=False),
    sa.Column('execution_mode', sa.Text(), nullable=False),
    sa.Column('timeout_s', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('backoff_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resource_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visibility_timeout_s', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.add_column('jobs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_jobs_lease_expires_at'), 'jobs', ['lease_expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_lease_expires_at'), table_name='jobs')
    op.drop_column('jobs', 'lease_expires_at')
    op.drop_table('job_definitions')
    # ### end Alembic commands ###
