"""add_queue_foreign_key_to_jobs

Revision ID: e9c5375c53e9
Revises: 89c142992d52
Create Date: 2026-01-17 20:38:05.865535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c5375c53e9'
down_revision: Union[str, Sequence[str], None] = '89c142992d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, ensure default queue exists
    op.execute("""
        INSERT INTO queues (name, max_concurrency, active)
        VALUES ('default', 10, true)
        ON CONFLICT (name) DO NOTHING
    """)
    
    # Create index first
    op.create_index(op.f('ix_jobs_queue'), 'jobs', ['queue'], unique=False)
    
    # Add foreign key constraint
    op.create_foreign_key(
        'fk_jobs_queue_name',
        'jobs', 
        'queues', 
        ['queue'], 
        ['name'], 
        ondelete='RESTRICT'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_jobs_queue_name', 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_queue'), table_name='jobs')
    # ### end Alembic commands ###
